steps:
  - name: "gcr.io/cloud-builders/yarn"
    id: "install"
    args: ["install"]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "decrypt .env"
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --project=lighthouse-scanner
      - --keyring=deploy
      - --key=env
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["decrypt .env"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then gcloud functions deploy scanDomain --runtime nodejs8 --memory=1024M --timeout=90s --trigger-http; else exit 0; fi
